[package]
name = "velodyne"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
byteorder = "1.0"
chrono = "0.3"
docopt = "0.7"
rustc-serialize = "0.3"
pcap = "0.5"

[[bin]]
name = "velodyne"
doc = false
test = false
